name       : headset-control
version    : 2.6.1
release    : 5
source     :
    - https://github.com/Sapd/HeadsetControl/archive/refs/tags/2.6.1.tar.gz : 13e4b32d5966e166e44bcfb85294ee08d600348437eee3b50e7cfa1ca96e62b5
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Sidetone and Battery status for Logitech G930, G533, G633, G933 SteelSeries Arctis 7/PRO 2019 and Corsair VOID (Pro)
description: |
    A tool to control certain aspects of USB-connected headsets on Linux. Currently, support is provided for adjusting sidetone, getting battery state, controlling LEDs, and setting the inactive time.
builddeps  :
    - pkgconfig(hidapi-libusb)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
