name       : headset-control
version    : '2.3'
release    : 1
source     :
    - https://github.com/Sapd/HeadsetControl/archive/2.3.tar.gz : 4969f13b5c5e2fee3b4b75d09f1a3ef1b707615aababf40d1f7cac60eab1fc21
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Sidetone and Battery status for Logitech G930, G533, G633, G933 SteelSeries Arctis 7/PRO 2019 and Corsair VOID (Pro)
description: |
    A tool to control certain aspects of USB-connected headsets on Linux. Currently, support is provided for adjusting sidetone, getting battery state, controlling LEDs, and setting the inactive time.
builddeps  :
    - pkgconfig(hidapi-libusb)
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
